#APP_ABI := arm64-v8a
APP_ABI := armeabi-v7a
APP_PLATFORM := android-21
APP_STL := gnustl_shared
APP_OPTIM := debug
#APP_OPTIM := release
#APP_CPPFLAGS += -frtti -fexceptions
NDK_TOOLCHAIN_VERSION := 4.9
#NDK_TOOLCHAIN_VERSION := clang
